name: docker-build-image

on:
  pull_request:

concurrency:
  group: "docker-build-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build docker images
        uses: ./.github/actions/docker-deploy
        with:
          image_name: ${{ github.repository }}
          push: false
